### ISSUE TITLE
Allow to compile with lts for ghc 9.4.7

### ISSUE THREAD

**Issue by worm2fed** [andremarianiello/hasql-transaction-io#5]
Could you please bump some bounds pls?
```
       In the dependencies for hasql-transaction-io-0.2.2.0:
         * base must match >=4.14 && <4.17, but base-4.17.2.0 is in the Stack configuration (latest matching version is 4.16.4.0).
       needed due to union-0.1.0 -> hasql-transaction-io-0.2.2.0
```

**Comment by worm2fed** [comment]
@andremarianiello 
wow, that was fast
many thanks!

**Comment by andremarianiello** [comment]
Release 0.2.3.0 which builds with ghc 9.4.7 https://hackage.haskell.org/package/hasql-transaction-io-0.2.3.0. Hope this helps!

Would you mind telling me a little bit about what you are using hasql-transaction-io for? Of course you do not have to tell me if you wish to keep it private, but I am curious about what people are using it for.

**Comment by worm2fed** [comment]
@andremarianiello sure

I have this base type and function:
```haskell
-- | 'TransactionIO' which may fail.
newtype Transaction error result = Transaction
  {runTransaction :: ExceptT error TransactionIO result}
  deriving newtype (Functor, Applicative, Monad, MonadIO, MonadError error)

-- | Creates 'Transaction' by given @params@ and 'Statement'.
transaction
  :: params
  -> Statement params (Either error result)
  -> Transaction error result
transaction params = Transaction . ExceptT . statement params
{-# INLINE transaction #-}
```

which are used in "interface", like this:
```haskell
type Tx = Sql.Transaction (ErrorWithSource IndividualContextError)

instance InterestRepository Tx where
  ...
 
  insertInterest :: Interest Local -> Tx InterestP
  insertInterest (toPersistent -> interest) =
    Sql.transaction () . fmap (throwOnNothing Logger.Error UnknownRepositoryError) $
      toDomain <<$>> Sql.insertOne interestSchema interest
```

Business logic uses that interface type class (so, do not rely on implementation):
```haskell
-- | Creates 'Interest'.
createInterest :: InterestRepository tx => CreateInterest -> tx InterestP
createInterest CreateInterest{..} = do
  R.insertInterest $
    Interest
      { iPk = Nothing
      , iName = T.strip ciName
      }
```

My custom newtype `Transaction` around `ExceptT` allows me to throw errors from domain and infra (implementation) layers.

and later, I connect all together:
```haskell
-- | Creates 'Interest' by given name.
createInterest
  :: (WithDb m, WithError m) => CreateInterest -> m IndividualInterest
createInterest = fmap toDto . runIndividualContext . D.createInterest
```

and bellow are helpers:
```haskell
-- | Runs Individual Context computations.
runIndividualContext
  :: (WithDb m, WithError m)
  => Sql.Transaction (ErrorWithSource IndividualContextError) a
  -> m a
runIndividualContext =
  withFrozenCallStack (Db.runTransaction @IndividualContextError)
{-# INLINE runIndividualContext #-}
```

```haskell
-- | Runs 'Sql.Transaction'. In case of error in any step it will rollback.
-- NOTE: because @hasql-transaction-io@ uses exceptions to rollback, we need
-- to throw an exception in case of Left and then turn it back to Left.
runTransaction
  :: (ToError e, With env m, Error.With Error m)
  => Sql.Transaction (ErrorWithSource e) a
  -> m a
runTransaction (Sql.runTransaction -> tx) = withFrozenCallStack do
  let action =
        runDb
          . transactionIO Serializable ReadWrite Deferrable
          $ runExceptT tx
            >>= either (pure . Left . AppException . fmap toError) (pure . Right)
            >>= fromEither
  action `catch` (E.throwError . getAppException)
```

In this examples there is no need in IO, but I do have places where I need to get current time or generate `UUID`, and I wanted to have everything at domain layer in same monad.


For now, honestly I'm very doubt about an idea to have each domain action in monad instead of pure transformations where it's possible.
Another concern is that even though I can provide different implementations for different contexts, but they to tight to `TransactionIO` and postgresql (I want to use neo4j for some parts of my application).


Generally, I wanted to implement kinda domain-driven-design for my web app. This design is still quite raw, but maybe you'll find it interesting.
Maybe one day I'll post something with this idea and maybe will wrap it to lib

hope I've answered your question)

**Comment by andremarianiello** [comment]
You did answer my question, thanks! Good luck on your journey!

**Comment by worm2fed** [comment]
Thanks!
